import { describe, it, expect } from "vitest";
import { escapeRegExp } from "./postgres";
import { parseAndImport } from "../sqlTestKit";
import { Cardinality, Constraint, DB } from "../../data/constants";

describe("escapeRegExp", () => {
  it("escapes regex metacharacters", () => {
    expect(escapeRegExp("a.b*c")).toBe("a\\.b\\*c");
  });

  it("leaves an ordinary identifier unchanged", () => {
    expect(escapeRegExp("my_enum")).toBe("my_enum");
  });
});

// Import feature-matrix: feed representative Postgres DDL per feature through the
// exact app flow (normalizeSQLForParser -> node-sql-parser -> fromPostgres) and
// assert the parsed diagram. `parseAndImport` is the sqlTestKit helper.
const imp = (sql) => parseAndImport(sql, DB.POSTGRES);
const table = (d, name) => d.tables.find((t) => t.name === name);
const field = (t, name) => t.fields.find((f) => f.name === name);

describe("fromPostgres import feature-matrix", () => {
  it("NOT NULL / DEFAULT literal / quoted-string default", () => {
    const d = imp(
      `CREATE TABLE t (
        a INTEGER NOT NULL,
        b INTEGER DEFAULT 5,
        c VARCHAR(20) DEFAULT 'active'
      );`,
    );
    const t = table(d, "t");
    expect(field(t, "a").notNull).toBe(true);
    expect(field(t, "b").notNull).toBe(false);
    expect(field(t, "b").default).toBe("5");
    expect(field(t, "c").default).toBe("active");
  });

  it("function defaults (now(), gen_random_uuid()) keep their call form", () => {
    const d = imp(
      `CREATE TABLE t (
        id UUID DEFAULT gen_random_uuid(),
        created TIMESTAMP DEFAULT now()
      );`,
    );
    const t = table(d, "t");
    expect(field(t, "id").default).toBe("gen_random_uuid()");
    expect(field(t, "created").default).toBe("now()");
  });

  it("UNIQUE column flag", () => {
    const d = imp(`CREATE TABLE t (email VARCHAR(255) UNIQUE);`);
    expect(field(table(d, "t"), "email").unique).toBe(true);
  });

  it("named single-column UNIQUE constraint", () => {
    const d = imp(
      `CREATE TABLE t (slug VARCHAR(100), CONSTRAINT uq_slug UNIQUE (slug));`,
    );
    const t = table(d, "t");
    expect(t.uniqueConstraints).toHaveLength(1);
    expect(t.uniqueConstraints[0].name).toBe("uq_slug");
    expect(t.uniqueConstraints[0].fields).toEqual(["slug"]);
  });

  it("composite UNIQUE constraint", () => {
    const d = imp(
      `CREATE TABLE t (a INT, b INT, CONSTRAINT uq UNIQUE (a, b));`,
    );
    expect(table(d, "t").uniqueConstraints[0].fields).toEqual(["a", "b"]);
  });

  it("plain and UNIQUE indexes, single and composite", () => {
    const d = imp(
      `CREATE TABLE t (a INT, b INT);
       CREATE INDEX idx_ab ON t (a, b);
       CREATE UNIQUE INDEX uidx_b ON t (b);`,
    );
    const t = table(d, "t");
    expect(t.indices).toHaveLength(2);
    const idx = t.indices.find((i) => i.name === "idx_ab");
    expect(idx.unique).toBe(false);
    expect(idx.fields).toEqual(["a", "b"]);
    const uidx = t.indices.find((i) => i.name === "uidx_b");
    expect(uidx.unique).toBe(true);
    expect(uidx.fields).toEqual(["b"]);
  });

  it("composite PRIMARY KEY marks every member column primary", () => {
    const d = imp(`CREATE TABLE t (a INT, b INT, c INT, PRIMARY KEY (a, b));`);
    const t = table(d, "t");
    expect(field(t, "a").primary).toBe(true);
    expect(field(t, "b").primary).toBe(true);
    expect(field(t, "c").primary).toBe(false);
  });

  it("SERIAL is carried as the column type", () => {
    const d = imp(`CREATE TABLE t (id SERIAL PRIMARY KEY);`);
    const id = field(table(d, "t"), "id");
    expect(id.type).toBe("SERIAL");
    expect(id.primary).toBe(true);
  });

  it("GENERATED BY DEFAULT AS IDENTITY sets increment (regression)", () => {
    // Regression for the fixed import gap: identity surfaces as
    // d.generated_by_default, not d.auto_increment.
    const d = imp(
      `CREATE TABLE t (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);`,
    );
    const id = field(table(d, "t"), "id");
    expect(id.type).toBe("INTEGER");
    expect(id.increment).toBe(true);
  });

  it("array column (ARRAY keyword) sets isArray (regression)", () => {
    const d = imp(`CREATE TABLE t (tags TEXT ARRAY);`);
    const tags = field(table(d, "t"), "tags");
    expect(tags.type).toBe("TEXT");
    expect(tags.isArray).toBe(true);
  });

  it("non-array column has isArray false", () => {
    const d = imp(`CREATE TABLE t (name TEXT);`);
    expect(field(table(d, "t"), "name").isArray).toBe(false);
  });

  it("COMMENT ON TABLE and COMMENT ON COLUMN", () => {
    const d = imp(
      `CREATE TABLE t (id INT);
       COMMENT ON TABLE t IS 'the table';
       COMMENT ON COLUMN t.id IS 'the id';`,
    );
    const t = table(d, "t");
    expect(t.comment).toBe("the table");
    expect(field(t, "id").comment).toBe("the id");
  });

  it("single-column inline FK with ON UPDATE/DELETE actions", () => {
    const d = imp(
      `CREATE TABLE u (id INT PRIMARY KEY);
       CREATE TABLE p (id INT PRIMARY KEY, uid INT REFERENCES u(id)
         ON DELETE CASCADE ON UPDATE RESTRICT);`,
    );
    expect(d.relationships).toHaveLength(1);
    const r = d.relationships[0];
    expect(r.startTableId).toBe(table(d, "p").id);
    expect(r.endTableId).toBe(table(d, "u").id);
    expect(r.deleteConstraint).toBe(Constraint.CASCADE);
    expect(r.updateConstraint).toBe(Constraint.RESTRICT);
    expect(r.cardinality).toBe(Cardinality.MANY_TO_ONE);
  });

  it("table-level single FK", () => {
    const d = imp(
      `CREATE TABLE u (id INT PRIMARY KEY);
       CREATE TABLE p (id INT PRIMARY KEY, uid INT,
         FOREIGN KEY (uid) REFERENCES u(id));`,
    );
    expect(d.relationships).toHaveLength(1);
    const r = d.relationships[0];
    expect(r.startTableId).toBe(table(d, "p").id);
    expect(r.endTableId).toBe(table(d, "u").id);
  });

  it("composite FOREIGN KEY yields a paired relationship", () => {
    const d = imp(
      `CREATE TABLE parent (a INT, b INT, PRIMARY KEY (a, b));
       CREATE TABLE child (a INT, b INT,
         FOREIGN KEY (a, b) REFERENCES parent(a, b));`,
    );
    expect(d.relationships).toHaveLength(1);
    const r = d.relationships[0];
    expect(r.fields).toHaveLength(2);
    const parent = table(d, "parent");
    const child = table(d, "child");
    expect(r.startTableId).toBe(child.id);
    expect(r.endTableId).toBe(parent.id);
    // both pairs resolve to real field ids in the right tables
    for (const p of r.fields) {
      expect(child.fields.some((f) => f.id === p.startFieldId)).toBe(true);
      expect(parent.fields.some((f) => f.id === p.endFieldId)).toBe(true);
    }
  });

  it("FK via ALTER TABLE ... ADD FOREIGN KEY", () => {
    const d = imp(
      `CREATE TABLE u (id INT PRIMARY KEY);
       CREATE TABLE p (id INT PRIMARY KEY, uid INT);
       ALTER TABLE p ADD FOREIGN KEY (uid) REFERENCES u(id) ON DELETE SET NULL;`,
    );
    expect(d.relationships).toHaveLength(1);
    const r = d.relationships[0];
    expect(r.startTableId).toBe(table(d, "p").id);
    expect(r.endTableId).toBe(table(d, "u").id);
    expect(r.deleteConstraint).toBe(Constraint.SET_NULL);
  });

  it("CREATE TYPE ... AS ENUM becomes an enum; a column references it", () => {
    const d = imp(
      `CREATE TYPE mood AS ENUM ('happy', 'sad');
       CREATE TABLE t (m mood);`,
    );
    expect(d.enums).toEqual([{ name: "mood", values: ["happy", "sad"] }]);
    expect(field(table(d, "t"), "m").type).toBe("mood");
  });

  it("CREATE TYPE ... AS (composite) becomes a type; a column references it", () => {
    const d = imp(
      `CREATE TYPE addr AS (street TEXT, zip INT);
       CREATE TABLE t (a addr);`,
    );
    expect(d.types).toHaveLength(1);
    expect(d.types[0].name).toBe("addr");
    expect(d.types[0].fields.map((f) => f.name)).toEqual(["street", "zip"]);
    expect(field(table(d, "t"), "a").type).toBe("addr");
  });

  it("CHECK constraint is captured on the field", () => {
    const d = imp(`CREATE TABLE t (age INTEGER CHECK (age > 0));`);
    expect(field(table(d, "t"), "age").check).toBeTruthy();
  });

  // shared.js buildSQLFromAST now reads column.expr.value for Postgres, so the
  // column name survives (quoted) instead of importing as "[object Object]".
  it("CHECK expression preserves the column name", () => {
    const d = imp(`CREATE TABLE t (age INTEGER CHECK (age > 0));`);
    const check = field(table(d, "t"), "age").check;
    expect(check).toContain("age");
    expect(check).not.toContain("[object Object]");
  });

  // shared.js now renders an expr_list as (a, b, ...) instead of joining with
  // " AND ", so an IN-list CHECK keeps its members.
  it("CHECK IN (...) preserves the value list", () => {
    const d = imp(`CREATE TABLE t (s VARCHAR(10) CHECK (s IN ('a', 'b')));`);
    expect(field(table(d, "t"), "s").check).toContain("'a'");
  });

  // The bracket array form (`TEXT[]`) folds "[]" into dataType; the importer
  // now strips it and sets isArray, matching the ARRAY keyword form.
  it("bracket array form TEXT[] resolves the type and sets isArray", () => {
    const d = imp(`CREATE TABLE t (tags TEXT[]);`);
    const tags = field(table(d, "t"), "tags");
    expect(tags.type).toBe("TEXT");
    expect(tags.isArray).toBe(true);
  });
});
