import { describe, it, expect } from "vitest";
import { toPostgres } from "./postgres";
import { roundTrip, LIVE_DB, runLiveDDL } from "../sqlTestKit";
import { generateMigrationSQL } from "../migrations/diffToSQL";
import { dbToTypes } from "../../data/datatypes";
import { DB } from "../../data/constants";

// ---- fixture builders -----------------------------------------------------

let SEQ = 0;
const fid = () => "f" + SEQ++;

function makeField(o = {}) {
  return {
    id: fid(),
    name: "col",
    type: "INTEGER",
    size: "",
    notNull: false,
    primary: false,
    unique: false,
    increment: false,
    default: "",
    check: "",
    comment: "",
    values: [],
    isArray: false,
    ...o,
  };
}

function makeTable(o = {}) {
  return {
    id: "t" + SEQ++,
    name: "t",
    comment: "",
    color: "#175e7a",
    indices: [],
    uniqueConstraints: [],
    inherits: [],
    fields: [],
    ...o,
  };
}

function makeDiagram(o = {}) {
  return {
    database: DB.POSTGRES,
    tables: [],
    references: [],
    enums: [],
    types: [],
    ...o,
  };
}

// ============================================================================
// (a) export feature-assertions
// ============================================================================

describe("toPostgres export clauses", () => {
  it("quotes identifiers and emits IF NOT EXISTS", () => {
    const sql = toPostgres(
      makeDiagram({
        tables: [
          makeTable({ name: "users", fields: [makeField({ name: "id" })] }),
        ],
      }),
    );
    expect(sql).toContain('CREATE TABLE IF NOT EXISTS "users"');
    expect(sql).toContain('"id"');
  });

  it("NOT NULL, UNIQUE, DEFAULT and CHECK clauses", () => {
    const sql = toPostgres(
      makeDiagram({
        tables: [
          makeTable({
            name: "t",
            fields: [
              makeField({ name: "email", type: "VARCHAR", size: 255, notNull: true, unique: true }),
              makeField({ name: "status", type: "VARCHAR", size: 20, default: "active" }),
              makeField({ name: "age", type: "INTEGER", check: "age >= 0" }),
            ],
          }),
        ],
      }),
    );
    expect(sql).toContain('"email" VARCHAR(255) NOT NULL UNIQUE');
    expect(sql).toContain(`"status" VARCHAR(20) DEFAULT 'active'`);
    expect(sql).toContain('"age" INTEGER CHECK(age >= 0)');
  });

  it("increment renders GENERATED BY DEFAULT AS IDENTITY", () => {
    const sql = toPostgres(
      makeDiagram({
        tables: [
          makeTable({
            name: "t",
            fields: [makeField({ name: "id", type: "INTEGER", increment: true, primary: true })],
          }),
        ],
      }),
    );
    expect(sql).toContain('"id" INTEGER GENERATED BY DEFAULT AS IDENTITY');
    expect(sql).toContain('PRIMARY KEY("id")');
  });

  it("array column renders the ARRAY keyword", () => {
    const sql = toPostgres(
      makeDiagram({
        tables: [
          makeTable({ name: "t", fields: [makeField({ name: "tags", type: "TEXT", isArray: true })] }),
        ],
      }),
    );
    expect(sql).toContain('"tags" TEXT ARRAY');
  });

  it("composite PRIMARY KEY", () => {
    const sql = toPostgres(
      makeDiagram({
        tables: [
          makeTable({
            name: "t",
            fields: [
              makeField({ name: "a", type: "INTEGER", primary: true }),
              makeField({ name: "b", type: "INTEGER", primary: true }),
            ],
          }),
        ],
      }),
    );
    expect(sql).toContain('PRIMARY KEY("a", "b")');
  });

  it("named UNIQUE constraint", () => {
    const sql = toPostgres(
      makeDiagram({
        tables: [
          makeTable({
            name: "t",
            fields: [makeField({ name: "slug", type: "VARCHAR", size: 100 })],
            uniqueConstraints: [{ id: 0, name: "uq_slug", fields: ["slug"] }],
          }),
        ],
      }),
    );
    expect(sql).toContain('CONSTRAINT "uq_slug" UNIQUE ("slug")');
  });

  it("table and column COMMENT ON statements", () => {
    const sql = toPostgres(
      makeDiagram({
        tables: [
          makeTable({
            name: "t",
            comment: "a table",
            fields: [makeField({ name: "id", comment: "the id" })],
          }),
        ],
      }),
    );
    expect(sql).toContain(`COMMENT ON TABLE "t" IS 'a table';`);
    expect(sql).toContain(`COMMENT ON COLUMN "t"."id" IS 'the id';`);
  });

  it("CREATE INDEX (plain and unique)", () => {
    const sql = toPostgres(
      makeDiagram({
        tables: [
          makeTable({
            name: "t",
            fields: [makeField({ name: "a" }), makeField({ name: "b" })],
            indices: [
              { id: 0, name: "idx_a", unique: false, fields: ["a"] },
              { id: 1, name: "uidx_b", unique: true, fields: ["b"] },
            ],
          }),
        ],
      }),
    );
    expect(sql).toContain('CREATE INDEX "idx_a"\nON "t" ("a");');
    expect(sql).toContain('CREATE UNIQUE INDEX "uidx_b"\nON "t" ("b");');
  });

  it("CREATE TYPE AS ENUM", () => {
    const sql = toPostgres(makeDiagram({ enums: [{ name: "mood", values: ["happy", "sad"] }] }));
    expect(sql).toContain('CREATE TYPE "mood" AS ENUM');
    expect(sql).toContain("'happy'");
    expect(sql).toContain("'sad'");
  });

  it("CREATE TYPE AS (composite) with a comment", () => {
    const sql = toPostgres(
      makeDiagram({
        types: [
          { name: "addr", comment: "an address", fields: [{ name: "street", type: "TEXT" }, { name: "zip", type: "INTEGER" }] },
        ],
      }),
    );
    expect(sql).toContain('CREATE TYPE "addr" AS (');
    expect(sql).toContain('"street" TEXT');
    expect(sql).toContain(`COMMENT ON TYPE "addr" IS 'an address';`);
  });

  it("INHERITS clause", () => {
    const sql = toPostgres(
      makeDiagram({
        tables: [
          makeTable({ name: "parent", fields: [makeField({ name: "id", primary: true })] }),
          makeTable({ name: "child", inherits: ["parent"], fields: [makeField({ name: "extra" })] }),
        ],
      }),
    );
    expect(sql).toContain(') INHERITS ("parent")');
  });

  it("foreign key ALTER TABLE with ON UPDATE / ON DELETE", () => {
    const uid = fid();
    const rid = fid();
    const sql = toPostgres(
      makeDiagram({
        tables: [
          makeTable({ id: "u", name: "u", fields: [makeField({ id: uid, name: "id", primary: true })] }),
          makeTable({ id: "p", name: "p", fields: [makeField({ id: rid, name: "uid" })] }),
        ],
        references: [
          {
            id: "r1",
            name: "fk",
            startTableId: "p",
            endTableId: "u",
            startFieldId: rid,
            endFieldId: uid,
            fields: [{ startFieldId: rid, endFieldId: uid }],
            updateConstraint: "Cascade",
            deleteConstraint: "Set null",
          },
        ],
      }),
    );
    expect(sql).toContain('ALTER TABLE "p"');
    expect(sql).toContain('ADD FOREIGN KEY("uid") REFERENCES "u"("id")');
    expect(sql).toContain("ON UPDATE CASCADE ON DELETE SET NULL");
  });
});

// ============================================================================
// (b) round-trip: diagram -> SQL -> parse -> diagram
// ============================================================================

describe("toPostgres round-trip", () => {
  it("preserves fields, flags, comments, unique constraint, index, enum, type and FK", () => {
    const uid = fid();
    const aid = fid();
    const diagram = makeDiagram({
      tables: [
        makeTable({
          id: "users",
          name: "users",
          comment: "the users",
          indices: [{ id: 0, name: "idx_email", unique: false, fields: ["email"] }],
          fields: [
            makeField({ id: uid, name: "id", type: "INTEGER", notNull: true, primary: true, increment: true }),
            makeField({ name: "email", type: "VARCHAR", size: 255, notNull: true, unique: true, comment: "the email" }),
            makeField({ name: "tags", type: "TEXT", isArray: true }),
            makeField({ name: "status", type: "VARCHAR", size: 20, default: "active" }),
            makeField({ name: "active", type: "BOOLEAN", default: "true" }),
          ],
        }),
        makeTable({
          id: "posts",
          name: "posts",
          uniqueConstraints: [{ id: 0, name: "uq_slug", fields: ["slug"] }],
          fields: [
            makeField({ name: "id", type: "INTEGER", primary: true, increment: true }),
            makeField({ id: aid, name: "author_id", type: "INTEGER" }),
            makeField({ name: "slug", type: "VARCHAR", size: 100 }),
          ],
        }),
      ],
      references: [
        {
          id: "r1",
          name: "fk_posts_author",
          startTableId: "posts",
          endTableId: "users",
          startFieldId: aid,
          endFieldId: uid,
          fields: [{ startFieldId: aid, endFieldId: uid }],
          updateConstraint: "Cascade",
          deleteConstraint: "Restrict",
        },
      ],
      enums: [{ name: "mood", values: ["happy", "sad"] }],
      // no type comment: COMMENT ON TYPE is valid PG but not re-parseable, so it
      // would break the round trip (documented in the design doc).
      types: [{ name: "addr", comment: "", fields: [{ name: "street", type: "TEXT" }, { name: "zip", type: "INTEGER" }] }],
    });

    const { imported } = roundTrip(diagram);

    const users = imported.tables.find((t) => t.name === "users");
    const f = (t, n) => t.fields.find((x) => x.name === n);
    expect(f(users, "id").increment).toBe(true);
    expect(f(users, "id").primary).toBe(true);
    expect(f(users, "email").unique).toBe(true);
    expect(f(users, "email").comment).toBe("the email");
    expect(f(users, "tags").isArray).toBe(true);
    expect(f(users, "status").default).toBe("active");
    expect(users.comment).toBe("the users");
    expect(users.indices.map((i) => i.name)).toContain("idx_email");

    const posts = imported.tables.find((t) => t.name === "posts");
    expect(posts.uniqueConstraints[0].name).toBe("uq_slug");

    expect(imported.relationships).toHaveLength(1);
    const r = imported.relationships[0];
    expect(r.startTableId).toBe(posts.id);
    expect(r.endTableId).toBe(users.id);
    expect(r.updateConstraint).toBe("Cascade");
    expect(r.deleteConstraint).toBe("Restrict");

    expect(imported.enums).toEqual([{ name: "mood", values: ["happy", "sad"] }]);
    expect(imported.types[0].name).toBe("addr");
    expect(imported.types[0].fields.map((x) => x.name)).toEqual(["street", "zip"]);
  });
});

// ============================================================================
// (c) dbToTypes[DB.POSTGRES] checkDefault unit tests
// ============================================================================

describe("dbToTypes[POSTGRES] checkDefault", () => {
  const pg = dbToTypes[DB.POSTGRES];
  const ok = (type, def, size) => pg[type].checkDefault({ default: def, size });

  it("INTEGER accepts integers, rejects decimals", () => {
    expect(ok("INTEGER", "5")).toBe(true);
    expect(ok("INTEGER", "-3")).toBe(true);
    expect(ok("INTEGER", "5.5")).toBe(false);
    expect(ok("INTEGER", "abc")).toBe(false);
  });

  it("NUMERIC accepts decimals", () => {
    expect(ok("NUMERIC", "5.5")).toBe(true);
    expect(ok("NUMERIC", "10")).toBe(true);
    expect(ok("NUMERIC", "abc")).toBe(false);
  });

  it("VARCHAR honours the size budget (quoted and unquoted)", () => {
    expect(ok("VARCHAR", "'active'", 10)).toBe(true);
    expect(ok("VARCHAR", "toolongvalue", 5)).toBe(false);
    expect(ok("VARCHAR", "'toolongvalue'", 5)).toBe(false);
  });

  it("CHAR honours the size budget", () => {
    expect(ok("CHAR", "'a'", 1)).toBe(true);
    expect(ok("CHAR", "ab", 1)).toBe(false);
  });

  it("BOOLEAN accepts true/false only", () => {
    expect(ok("BOOLEAN", "true")).toBe(true);
    expect(ok("BOOLEAN", "FALSE")).toBe(true);
    expect(ok("BOOLEAN", "1")).toBe(false);
  });

  it("UUID validates the canonical form", () => {
    expect(ok("UUID", "123e4567-e89b-12d3-a456-426614174000")).toBe(true);
    expect(ok("UUID", "not-a-uuid")).toBe(false);
  });

  it("DATE accepts ISO dates and special values", () => {
    expect(ok("DATE", "2020-01-01")).toBe(true);
    expect(ok("DATE", "now")).toBe(true);
    expect(ok("DATE", "nonsense")).toBe(false);
  });

  it("TIMESTAMP accepts a full timestamp and current_timestamp", () => {
    expect(ok("TIMESTAMP", "2020-01-01 00:00:00")).toBe(true);
    expect(ok("TIMESTAMP", "current_timestamp")).toBe(true);
  });

  it("BIT accepts a bitstring", () => {
    expect(ok("BIT", "1010")).toBe(true);
    expect(ok("BIT", "12")).toBe(false);
  });

  it("JSON accepts anything (no default validation)", () => {
    expect(ok("JSON", '{"a":1}')).toBe(true);
  });

  // FLAG (data/datatypes.js, shared/forbidden to edit): the TIMESTAMP validator
  // has an OR-branch that accepts anything whose leading YYYY is 1970..2038, so
  // a garbage value like "1999-13-45 99:99:99" passes. Documented, not fixed.
  it.fails("TIMESTAMP should reject an impossible date (catalog looseness)", () => {
    expect(ok("TIMESTAMP", "1999-13-45 99:99:99")).toBe(false);
  });
});

// ============================================================================
// (d) Postgres generateMigrationSQL ALTER assertions
// ============================================================================

describe("generateMigrationSQL (Postgres ALTER paths)", () => {
  const T = "tables[id=1,name=users]";
  const col = (extra) => `${T}#fields[id=10,name=age,type=INTEGER]${extra}`;
  const tbl = (id, name, fields = []) => ({ id, name, comment: "", inherits: [], uniqueConstraints: [], indices: [], fields });
  const fld = (o) => makeField(o);

  it("add column -> ADD COLUMN up / DROP COLUMN down", () => {
    const to = { tables: [tbl(1, "users", [fld({ id: 10, name: "age", type: "INTEGER", default: "0" })])] };
    const from = { tables: [tbl(1, "users", [])] };
    const { up, down } = generateMigrationSQL(
      { [col("")]: { to: to.tables[0].fields[0], from: null } },
      DB.POSTGRES,
      { from, to },
    );
    expect(up).toMatch(/ALTER TABLE "users" ADD COLUMN "age" INTEGER/);
    expect(down).toMatch(/ALTER TABLE "users" DROP COLUMN "age"/);
  });

  it("type change -> ALTER COLUMN ... TYPE", () => {
    const { up, down } = generateMigrationSQL(
      { [col("#type")]: { from: "INTEGER", to: "BIGINT" } },
      DB.POSTGRES,
      { from: {}, to: {} },
    );
    expect(up).toContain('ALTER TABLE "users" ALTER COLUMN "age" TYPE BIGINT;');
    expect(down).toContain('ALTER TABLE "users" ALTER COLUMN "age" TYPE INTEGER;');
  });

  it("notNull -> SET/DROP NOT NULL", () => {
    const { up, down } = generateMigrationSQL(
      { [col("#notNull")]: { from: false, to: true } },
      DB.POSTGRES,
      { from: {}, to: {} },
    );
    expect(up).toContain('SET NOT NULL');
    expect(down).toContain('DROP NOT NULL');
  });

  it("default -> SET DEFAULT / DROP DEFAULT", () => {
    const { up, down } = generateMigrationSQL(
      { [col("#default")]: { from: "", to: "0" } },
      DB.POSTGRES,
      { from: {}, to: {} },
    );
    expect(up).toContain('ALTER TABLE "users" ALTER COLUMN "age" SET DEFAULT 0;');
    expect(down).toContain('DROP DEFAULT');
  });

  it("check -> ADD/DROP CONSTRAINT", () => {
    const { up, down } = generateMigrationSQL(
      { [col("#check")]: { from: "", to: "age > 0" } },
      DB.POSTGRES,
      { from: {}, to: {} },
    );
    expect(up).toMatch(/ADD CONSTRAINT "users_age_check" CHECK \(age > 0\)/);
    expect(down).toMatch(/DROP CONSTRAINT "users_age_check"/);
  });

  it("increment -> ADD/DROP IDENTITY", () => {
    const { up, down } = generateMigrationSQL(
      { [col("#increment")]: { from: false, to: true } },
      DB.POSTGRES,
      { from: {}, to: {} },
    );
    expect(up).toContain('ADD GENERATED BY DEFAULT AS IDENTITY');
    expect(down).toContain('DROP IDENTITY');
  });

  it("isArray -> TYPE ...[] USING", () => {
    const { up, down } = generateMigrationSQL(
      { [col("#isArray")]: { from: false, to: true } },
      DB.POSTGRES,
      { from: {}, to: {} },
    );
    expect(up).toContain('TYPE INTEGER[] USING "age"::INTEGER[];');
    expect(down).toContain('USING "age"[1];');
  });

  it("size -> ALTER COLUMN ... TYPE type(size)", () => {
    const path = `${T}#fields[id=10,name=name,type=VARCHAR]#size`;
    const { up } = generateMigrationSQL(
      { [path]: { from: "50", to: "100" } },
      DB.POSTGRES,
      { from: {}, to: {} },
    );
    expect(up).toContain('ALTER TABLE "users" ALTER COLUMN "name" TYPE VARCHAR(100);');
  });

  it("rename column -> RENAME COLUMN", () => {
    const { up, down } = generateMigrationSQL(
      { [col("#name")]: { from: "age", to: "years" } },
      DB.POSTGRES,
      { from: {}, to: {} },
    );
    expect(up).toContain('RENAME COLUMN "age" TO "years";');
    expect(down).toContain('RENAME COLUMN "years" TO "age";');
  });

  it("unique -> ADD/DROP CONSTRAINT UNIQUE", () => {
    const { up } = generateMigrationSQL(
      { [col("#unique")]: { from: false, to: true } },
      DB.POSTGRES,
      { from: {}, to: {} },
    );
    expect(up).toMatch(/ADD CONSTRAINT "users_age_unique" UNIQUE \("age"\)/);
  });

  it("primary -> ADD/DROP CONSTRAINT PRIMARY KEY", () => {
    const { up } = generateMigrationSQL(
      { [col("#primary")]: { from: false, to: true } },
      DB.POSTGRES,
      { from: {}, to: {} },
    );
    expect(up).toMatch(/ADD CONSTRAINT "users_pkey" PRIMARY KEY \("age"\)/);
  });

  it("add foreign key relationship -> ADD CONSTRAINT ... FOREIGN KEY", () => {
    const to = {
      tables: [
        tbl("u", "u", [fld({ id: "u1", name: "id", primary: true })]),
        tbl("p", "p", [fld({ id: "p1", name: "uid" })]),
      ],
      relationships: [
        {
          id: "r1",
          name: "fk_p_u",
          startTableId: "p",
          endTableId: "u",
          fields: [{ startFieldId: "p1", endFieldId: "u1" }],
          updateConstraint: "Cascade",
          deleteConstraint: "No action",
        },
      ],
    };
    const { up, down } = generateMigrationSQL(
      { "relationships[id=r1]": { to: to.relationships[0], from: null } },
      DB.POSTGRES,
      { from: { tables: to.tables, relationships: [] }, to },
    );
    expect(up).toMatch(/ALTER TABLE "p" ADD CONSTRAINT "fk_p_u" FOREIGN KEY \("uid"\) REFERENCES "u" \("id"\)/);
    expect(up).toContain("ON UPDATE CASCADE ON DELETE NO ACTION");
    expect(down).toMatch(/ALTER TABLE "p" DROP CONSTRAINT "fk_p_u"/);
  });

  it("add enum -> CREATE TYPE AS ENUM / DROP TYPE", () => {
    const e = { name: "mood", values: ["happy", "sad"] };
    const { up, down } = generateMigrationSQL(
      { "enums[id=0,name=mood]": { to: e, from: null } },
      DB.POSTGRES,
      { from: {}, to: {} },
    );
    expect(up).toContain('CREATE TYPE "mood" AS ENUM');
    expect(down).toContain('DROP TYPE "mood";');
  });

  it("add composite type -> CREATE TYPE AS (...)", () => {
    const ty = { name: "addr", comment: "", fields: [{ name: "street", type: "TEXT" }] };
    const { up } = generateMigrationSQL(
      { "types[id=0,name=addr]": { to: ty, from: null } },
      DB.POSTGRES,
      { from: {}, to: {} },
    );
    expect(up).toContain('CREATE TYPE "addr" AS (');
    expect(up).toContain('"street" TEXT');
  });

  it("inherits -> INHERIT / NO INHERIT", () => {
    const { up, down } = generateMigrationSQL(
      { "tables[id=1,name=child]#inherits#0": { from: null, to: "parent" } },
      DB.POSTGRES,
      { from: {}, to: {} },
    );
    expect(up).toContain('ALTER TABLE "child" INHERIT "parent";');
    expect(down).toContain('ALTER TABLE "child" NO INHERIT "parent";');
  });
});

// ============================================================================
// (e) live-engine validation against the current PostgreSQL release
// ============================================================================

(LIVE_DB ? describe : describe.skip)("live postgres", () => {
  const expectOk = (sql) => {
    const res = runLiveDDL("postgres", sql);
    expect(res.ok, res.error).toBe(true);
  };

  it("accepts a full-feature table (IDENTITY, ARRAY, CHECK, DEFAULT, UNIQUE, PK, index, comments)", () => {
    const sql = toPostgres(
      makeDiagram({
        tables: [
          makeTable({
            name: "users",
            comment: "the users",
            indices: [{ id: 0, name: "idx_email", unique: true, fields: ["email"] }],
            fields: [
              makeField({ name: "id", type: "INTEGER", notNull: true, primary: true, increment: true }),
              makeField({ name: "email", type: "VARCHAR", size: 255, notNull: true, unique: true, comment: "the email" }),
              makeField({ name: "age", type: "INTEGER", check: "age >= 0" }),
              makeField({ name: "tags", type: "TEXT", isArray: true }),
              makeField({ name: "status", type: "VARCHAR", size: 20, default: "active" }),
              makeField({ name: "created", type: "TIMESTAMP", default: "now()" }),
              makeField({ name: "active", type: "BOOLEAN", default: "true" }),
            ],
          }),
        ],
      }),
    );
    expectOk(sql);
  });

  it("accepts a composite PK and a named UNIQUE constraint", () => {
    const sql = toPostgres(
      makeDiagram({
        tables: [
          makeTable({
            name: "membership",
            uniqueConstraints: [{ id: 0, name: "uq_mem", fields: ["team", "person"] }],
            fields: [
              makeField({ name: "team", type: "INTEGER", primary: true }),
              makeField({ name: "person", type: "INTEGER", primary: true }),
            ],
          }),
        ],
      }),
    );
    expectOk(sql);
  });

  it("accepts an enum, a composite type (with comment), and columns using them", () => {
    const sql = toPostgres(
      makeDiagram({
        enums: [{ name: "mood", values: ["happy", "sad"] }],
        types: [{ name: "addr", comment: "an address", fields: [{ name: "street", type: "TEXT" }, { name: "zip", type: "INTEGER" }] }],
        tables: [
          makeTable({
            name: "profile",
            fields: [
              makeField({ name: "id", type: "INTEGER", primary: true, increment: true }),
              makeField({ name: "m", type: "mood" }),
              makeField({ name: "a", type: "addr" }),
            ],
          }),
        ],
      }),
    );
    expectOk(sql);
  });

  it("accepts single and composite foreign keys", () => {
    const uid = fid();
    const paId = fid();
    const pbId = fid();
    const caId = fid();
    const cbId = fid();
    const fkId = fid();
    const sql = toPostgres(
      makeDiagram({
        tables: [
          makeTable({ id: "u", name: "u", fields: [makeField({ id: uid, name: "id", type: "INTEGER", primary: true })] }),
          makeTable({ id: "child1", name: "child1", fields: [makeField({ id: fkId, name: "uid", type: "INTEGER" })] }),
          makeTable({
            id: "parent2",
            name: "parent2",
            fields: [makeField({ id: paId, name: "a", type: "INTEGER", primary: true }), makeField({ id: pbId, name: "b", type: "INTEGER", primary: true })],
          }),
          makeTable({
            id: "child2",
            name: "child2",
            fields: [makeField({ id: caId, name: "a", type: "INTEGER" }), makeField({ id: cbId, name: "b", type: "INTEGER" })],
          }),
        ],
        references: [
          {
            id: "r1", name: "fk1", startTableId: "child1", endTableId: "u",
            startFieldId: fkId, endFieldId: uid,
            fields: [{ startFieldId: fkId, endFieldId: uid }],
            updateConstraint: "Cascade", deleteConstraint: "Set null",
          },
          {
            id: "r2", name: "fk2", startTableId: "child2", endTableId: "parent2",
            startFieldId: caId, endFieldId: paId,
            fields: [{ startFieldId: caId, endFieldId: paId }, { startFieldId: cbId, endFieldId: pbId }],
            updateConstraint: "No action", deleteConstraint: "No action",
          },
        ],
      }),
    );
    expectOk(sql);
  });

  it("accepts an INHERITS child table", () => {
    const sql = toPostgres(
      makeDiagram({
        tables: [
          makeTable({ name: "parent", fields: [makeField({ name: "id", type: "INTEGER", primary: true, increment: true })] }),
          makeTable({ name: "child", inherits: ["parent"], fields: [makeField({ name: "extra", type: "TEXT" })] }),
        ],
      }),
    );
    expectOk(sql);
  });
});
