import {
  exportFieldComment,
  parseDefault,
  uniqueConstraintClause,
  getFkColumnNames,
} from "./shared";
import {
  quoterFor,
  safeConstraint,
  assertNoStatementBreak,
  assertSafeSize,
  assertSafeType,
  escapeQuotes,
} from "./sqlSafety";
import { dbToTypes } from "../../data/datatypes";
import { DB } from "../../data/constants";

export function toPostgres(diagram) {
  const q = quoterFor(DB.POSTGRES);

  const enumStatements = diagram.enums
    .map(
      (e) =>
        `CREATE TYPE ${q(e.name)} AS ENUM (\n${e.values
          .map((v) => `\t'${escapeQuotes(String(v))}'`)
          .join(",\n")}\n);\n`,
    )
    .join("\n");

  const typeStatements = diagram.types
    .map(
      (type) =>
        `CREATE TYPE ${q(type.name)} AS (\n${type.fields
          .map((f) => `\t${q(f.name)} ${assertSafeType(f.type)}`)
          .join(",\n")}\n);\n\n${
          type.comment?.trim()
            ? `COMMENT ON TYPE ${q(type.name)} IS '${escapeQuotes(type.comment)}';\n`
            : ""
        }`,
    )
    .join("\n");

  const tableStatements = diagram.tables
    .map((table) => {
      const inheritsClause =
        Array.isArray(table.inherits) && table.inherits.length > 0
          ? `\n) INHERITS (${table.inherits.map((parent) => q(parent)).join(", ")})`
          : "\n)";

      const fieldDefinitions = table.fields
        .map(
          (field) =>
            `${exportFieldComment(field.comment)}\t${q(
              field.name,
            )} ${assertSafeType(field.type)}${
              field.size ? `(${assertSafeSize(field.size)})` : ""
            }${field.isArray ? " ARRAY" : ""}${field.notNull ? " NOT NULL" : ""}${
              field.unique ? " UNIQUE" : ""
            }${field.increment ? " GENERATED BY DEFAULT AS IDENTITY" : ""}${
              field.default?.trim()
                ? ` DEFAULT ${parseDefault(field, diagram.database)}`
                : ""
            }${
              field.check && dbToTypes[diagram.database][field.type]?.hasCheck
                ? ` CHECK(${assertNoStatementBreak(field.check)})`
                : ""
            }`,
        )
        .join(",\n");

      const primaryKeyClause = table.fields.some((f) => f.primary)
        ? `,\n\tPRIMARY KEY(${table.fields
            .filter((f) => f.primary)
            .map((f) => q(f.name))
            .join(", ")})`
        : "";

      const uniqueClause = uniqueConstraintClause(table, q);

      const commentStatements = [
        table.comment?.trim()
          ? `COMMENT ON TABLE ${q(table.name)} IS '${escapeQuotes(table.comment)}';`
          : "",
        ...table.fields
          .map((field) =>
            field.comment?.trim()
              ? `COMMENT ON COLUMN ${q(table.name)}.${q(field.name)} IS '${escapeQuotes(field.comment)}';`
              : "",
          )
          .filter(Boolean),
      ].join("\n");

      const indexStatements = table.indices
        .map(
          (i) =>
            `CREATE ${i.unique ? "UNIQUE " : ""}INDEX ${q(i.name)}\nON ${q(table.name)} (${i.fields
              .map((f) => q(f))
              .join(", ")});`,
        )
        .join("\n");

      return `CREATE TABLE IF NOT EXISTS ${q(table.name)} (\n${fieldDefinitions}${primaryKeyClause}${uniqueClause}${inheritsClause};\n\n${commentStatements}\n${indexStatements}`;
    })
    .join("\n\n");

  const foreignKeyStatements = diagram.references
    .map((r) => {
      const startTable = diagram.tables.find((t) => t.id === r.startTableId);
      const endTable = diagram.tables.find((t) => t.id === r.endTableId);

      if (!startTable || !endTable) return "";

      const { startColumns, endColumns } = getFkColumnNames(
        r,
        startTable,
        endTable,
      );
      if (startColumns.some((c) => !c) || endColumns.some((c) => !c)) return "";

      return `ALTER TABLE ${q(startTable.name)}\nADD FOREIGN KEY(${startColumns
        .map((c) => q(c))
        .join(", ")}) REFERENCES ${q(endTable.name)}(${endColumns
        .map((c) => q(c))
        .join(
          ", ",
        )})\nON UPDATE ${safeConstraint(r.updateConstraint)} ON DELETE ${safeConstraint(r.deleteConstraint)};`;
    })
    .filter(Boolean)
    .join("\n");

  return [
    enumStatements,
    enumStatements.trim() && typeStatements
      ? "\n" + typeStatements
      : typeStatements,
    tableStatements,
    foreignKeyStatements,
  ]
    .filter(Boolean)
    .join("\n");
}
